# Generated by Django 2.2.4 on 2019-12-13 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191213_2029'),
    ]

    
