# Generated by Django 2.2.4 on 2019-12-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191213_2056'),
    ]

    operations = [
       
    ]
