# Generated by Django 2.2.4 on 2020-03-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191213_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='defaultA.jpg', upload_to='article_pics'),
        ),
    ]
